# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f5a049feb4251a0e43d92d63fe2ce76be1a2b95e4f4c37b818a42b9b17f8256044ed6ee9009eb76be3f9f952dfa00bce59193b826d0978c546f644d94b18cc2

test:
  secret_key_base: 087fc7f576c4b678ec1110c5bc679bc37b09e9abdd033996f68e924d05eb792658c735d7006a1b9fa8fccf683a1fd9eda2ee0067a4af52068e38ee38f14a9278

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
